"""empty message

Revision ID: 21a3f9ff4004
Revises: afa3ee6e3387
Create Date: 2023-11-20 01:35:55.865865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a3f9ff4004'
down_revision = 'afa3ee6e3387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isInCart', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('isInCart')

    # ### end Alembic commands ###
