"""empty message

Revision ID: 21cb4eadbf12
Revises: 
Create Date: 2023-11-13 22:23:05.875477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cb4eadbf12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('authorID', sa.SmallInteger(), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('authorID')
    )
    op.create_table('branch',
    sa.Column('branchID', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('branchID')
    )
    op.create_table('item_type',
    sa.Column('typeID', sa.Integer(), nullable=False),
    sa.Column('typeName', sa.String(length=20), nullable=True),
    sa.Column('rentDuration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('typeID')
    )
    op.create_table('patron',
    sa.Column('patronID', sa.SmallInteger(), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('phoneNum', sa.String(length=10), nullable=True),
    sa.Column('acctBalance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('itemsRented', sa.SmallInteger(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('patronID')
    )
    op.create_table('item',
    sa.Column('itemID', sa.SmallInteger(), nullable=False),
    sa.Column('itemTitle', sa.String(length=50), nullable=True),
    sa.Column('publishDate', sa.Date(), nullable=True),
    sa.Column('itemBranch', sa.String(length=50), nullable=True),
    sa.Column('typeID', sa.SmallInteger(), nullable=True),
    sa.Column('isCheckedOut', sa.Boolean(), nullable=False),
    sa.Column('isAvailable', sa.Boolean(), nullable=False),
    sa.Column('itemCondition', sa.String(length=50), nullable=True),
    sa.Column('isSecure', sa.Boolean(), nullable=False),
    sa.Column('inTransit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['typeID'], ['item_type.typeID'], ),
    sa.PrimaryKeyConstraint('itemID')
    )
    op.create_table('checkin',
    sa.Column('patronID', sa.SmallInteger(), nullable=True),
    sa.Column('itemID', sa.SmallInteger(), nullable=True),
    sa.Column('checkinID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('returnDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['itemID'], ['item.itemID'], ),
    sa.ForeignKeyConstraint(['patronID'], ['patron.patronID'], ),
    sa.PrimaryKeyConstraint('checkinID')
    )
    op.create_table('checkout',
    sa.Column('checkoutID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patronID', sa.SmallInteger(), nullable=True),
    sa.Column('itemID', sa.SmallInteger(), nullable=True),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['itemID'], ['item.itemID'], ),
    sa.ForeignKeyConstraint(['patronID'], ['patron.patronID'], ),
    sa.PrimaryKeyConstraint('checkoutID')
    )
    op.create_table('item_authors',
    sa.Column('authorID', sa.SmallInteger(), nullable=False),
    sa.Column('itemID', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['authorID'], ['author.authorID'], ),
    sa.ForeignKeyConstraint(['itemID'], ['item.itemID'], ),
    sa.PrimaryKeyConstraint('authorID', 'itemID')
    )
    op.create_table('item_branch',
    sa.Column('branchID', sa.SmallInteger(), nullable=False),
    sa.Column('itemID', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branchID'], ['branch.branchID'], ),
    sa.ForeignKeyConstraint(['itemID'], ['item.itemID'], ),
    sa.PrimaryKeyConstraint('branchID', 'itemID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_branch')
    op.drop_table('item_authors')
    op.drop_table('checkout')
    op.drop_table('checkin')
    op.drop_table('item')
    op.drop_table('patron')
    op.drop_table('item_type')
    op.drop_table('branch')
    op.drop_table('author')
    # ### end Alembic commands ###
