"""empty message

Revision ID: d1484109241b
Revises: 6f0dfab9b2cf
Create Date: 2023-11-26 15:59:04.880186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1484109241b'
down_revision = '6f0dfab9b2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cartStatus', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('cartStatus')

    # ### end Alembic commands ###
