"""empty message

Revision ID: d4190b70141f
Revises: f090e91c73cb
Create Date: 2023-11-28 21:47:33.695371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4190b70141f'
down_revision = 'f090e91c73cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patron', schema=None) as batch_op:
        batch_op.alter_column('phoneNum',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patron', schema=None) as batch_op:
        batch_op.alter_column('phoneNum',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
