"""empty message

Revision ID: ec2500df2abc
Revises: 
Create Date: 2023-11-06 14:20:14.506377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2500df2abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('authorID', sa.SmallInteger(), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('authorID')
    )
    op.create_table('item_type',
    sa.Column('typeID', sa.Integer(), nullable=False),
    sa.Column('typeName', sa.String(length=20), nullable=True),
    sa.Column('rentDuration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('typeID')
    )
    op.create_table('patron',
    sa.Column('patronID', sa.SmallInteger(), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('phoneNum', sa.String(length=10), nullable=True),
    sa.Column('acctBalance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('itemsRented', sa.SmallInteger(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('patronID')
    )
    op.create_table('item',
    sa.Column('itemID', sa.SmallInteger(), nullable=False),
    sa.Column('itemTitle', sa.String(length=50), nullable=True),
    sa.Column('publishDate', sa.Date(), nullable=True),
    sa.Column('itemBranch', sa.String(length=50), nullable=True),
    sa.Column('typeID', sa.SmallInteger(), nullable=True),
    sa.Column('isCheckedOut', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['typeID'], ['item_type.typeID'], ),
    sa.PrimaryKeyConstraint('itemID')
    )
    op.create_table('checkout',
    sa.Column('checkoutID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patronID', sa.SmallInteger(), nullable=True),
    sa.Column('itemID', sa.SmallInteger(), nullable=True),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['itemID'], ['item.itemID'], ),
    sa.ForeignKeyConstraint(['patronID'], ['patron.patronID'], ),
    sa.PrimaryKeyConstraint('checkoutID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkout')
    op.drop_table('item')
    op.drop_table('patron')
    op.drop_table('item_type')
    op.drop_table('author')
    # ### end Alembic commands ###
